export const scalarConfig = {
  hideClientButton: true,
  showSidebar: true,
  showDeveloperTools: "localhost",
  showToolbar: "localhost",
  operationTitleSource: "summary",
  theme: "alternate",
  persistAuth: false,
  telemetry: true,
  layout: "modern",
  isEditable: false,
  isLoading: false,
  hideModels: false,
  documentDownloadType: "none",
  hideTestRequestButton: false,
  hideSearch: false,
  showOperationId: false,
  hideDarkModeToggle: false,
  withDefaultFonts: true,
  defaultOpenAllTags: false,
  expandAllModelSections: false,
  expandAllResponses: false,
  orderSchemaPropertiesBy: "alpha",
  orderRequiredPropertiesFirst: true,
  _integration: "elysiajs",
  default: false,
  slug: "elysia-get-started",
  title: "Elysia Get Started",
};
